FROM mesosphere/python-monitoring:latest
MAINTAINER Mesosphere, Inc. <support@mesosphere.io>

ADD http://ftp.debian.org/debian/pool/main/l/linkchecker/linkchecker_9.3-1_amd64.deb /tmp/linkchecker_9.3-1_amd64.deb

RUN dpkg -i /tmp/linkchecker_9.3-1_amd64.deb